### ISSUE TITLE
Enhancement: allow separate heating and cooling thermostats in one dial

### ISSUE THREAD

**Issue by Spartan-II-117** [ciotlosm/custom-lovelace#211]
It would be great to have one unified dial for both heat and Air Conditioning show up, even if you are usng separate thermostats (such as z-wave) for the actual thermostat.

**Comment by ciotlosm** [comment]
I think that would make more sense to be a separate card. Not hard to do, but the complexity added for the current card would not be worth it. I will have to think how to write code for this to avoid duplication.

**Comment by Spartan-II-117** [comment]
Awesome

**Comment by tomeeka** [comment]
I am using conditional cards and button cards for that purpose. (conditional card is broken in 0.81, but I hope that will be fixed in the next release)

![kep](https://user-images.githubusercontent.com/41842441/47909232-910c6b80-de8f-11e8-99b2-17909c45d902.png)

**Comment by mar005** [comment]
Not sure if there is any headway here? I have a zwave thermostat that creates 4 entities of which I only use 2 to set a range for the highest temp and the lowest temp allowed and the thermostat decides if it cools or heats. I like this feature and I just change dynamically the range based on the occupancy of the house. However, as I am now trying to use the lovelace UI more on mobile instead of homekit it would be nice to have this nice looking and small thermostat for 1 thermostat. Currently I am using [this card](https://github.com/enriqg9/dual-thermostat ) for my desktop view but I use my phone more than anything. This card is just a bit too big for it to fit nicely in the phone given I have 2 physical thermostats (upstairs and downstairs).

**Comment by iantrich** [comment]
This card is no longer actively maintained
